### ISSUE TITLE
Potential database connections leaks from pool with Sidekiq.transactional_push!

### ISSUE THREAD

**Issue by Galathius** [sidekiq-scheduler/sidekiq-scheduler#386]
Please check these issues:
- https://github.com/Envek/after_commit_everywhere/issues/20
- https://github.com/mperham/sidekiq/issues/5385

Probably, would be better to adjust `sidekiq-scheduler` for pushing jobs within a **Rails Executor**.

**Comment by marcelolx** [comment]
Interesting! I'll take a look into it @Galathius once I have some free time, thanks for the report!

**Comment by marcelolx** [comment]
Hey @Galathius, I don't think `sidekiq-scheduler` might be causing this leak because it just pushes the jobs to Redis, who definitely runs the Job is Sidekiq which runs it within the Executor. 

I see that https://github.com/Envek/after_commit_everywhere/issues/20 had some updates after this issue was created, do you still see connections being leaked?

**Comment by marcelolx** [comment]
Anyway I'll be working to enqueue the jobs within a Executor when it is running on a Rails app

**Comment by Galathius** [comment]
Hi! Now, with the latest fix for `after_commit_everywhere` gem, connections are not leaking anymore.

**Comment by marcelolx** [comment]
I will close this for now, but if someone else faces this again, please open an issue and we can take a look
