### ISSUE TITLE
Raises an exception when rufus_scheduler_options is nil by default

### ISSUE THREAD

**Issue by istana** [sidekiq-scheduler/sidekiq-scheduler#426]
Hi, I bumped into probably a bug - I believe `rufus_scheduler_options` should be set to empty hash instead of nil in an initializer. Versions are `sidekiq-scheduler (5.0.1)`, `rufus-scheduler (3.8.2)`.

Here is a minimal example:

```
require 'sidekiq/capsule'
SidekiqScheduler::Scheduler.instance.enabled = true
Sidekiq.schedule = {}
SidekiqScheduler::Scheduler.instance.reload_schedule!
```

fails with:

```
NoMethodError: undefined method `[]' for nil:NilClass
from /usr/src/app/vendor/bundle/ruby/3.0.0/gems/rufus-scheduler-3.8.2/lib/rufus/scheduler.rb:67:in `initialize'
```

However it works when `rufus_scheduler_options` is set to `{}`:

```
require 'sidekiq/capsule'
SidekiqScheduler::Scheduler.instance.enabled = true
SidekiqScheduler::Scheduler.instance.rufus_scheduler_options = {}
Sidekiq.schedule = {}
SidekiqScheduler::Scheduler.instance.reload_schedule!
```

**Comment by marcelolx** [comment]
Hmm interesting! Thanks for the report @istana, I will run some tests and come up with a fix when I have some time

**Comment by marcelolx** [comment]
Got the test working @samsm (was just missing the `require 'sidekiq/capsule'`, but I think this probably is not going to solve the problem alone, this seems to be related to https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/419

**Comment by marcelolx** [comment]
@istana we fixed this particular problem in https://github.com/sidekiq-scheduler/sidekiq-scheduler/commit/1092b96ce99fc2b78704af6ec42febfee5abfa99, but since I see you're requiring `sidekiq/capsule` in your code, I think it probably is related to this issue https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/419; Feel free to try again with the changes we made, but I think it probably won't be enough to make it work with Sidekiq in Embed mode

**Comment by istana** [comment]
Thanks. I had to require `sidekiq/capsule` to show it on a simple example, in reality I have a schedule generator which sets and reloads.
