### ISSUE TITLE
Sidekiq version requirement

### ISSUE THREAD

**Issue by JIucToyxuu** [sidekiq-scheduler/sidekiq-scheduler#429]
Hello! I'm little bit confused by CHANGELOG. By info from this, 5.x version include some breaking changes. And one from changes is drop support some Sidekiq versions(4.x, 5.x). But, 5.x version was released and still keep Sidekiq 4+ in dependencies. So, what is correct? Can I use Sidekiq 5.x version with this gem(5.x version)?

**Comment by marcelolx** [comment]
@JIucToyxuu I think we just unintentionally did revert that change in the gemspec because in the PR, we did drop the support we did bump the version https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/411/files

> So, what is correct? Can I use Sidekiq 5.x version with this gem(5.x version)?

We highly recommend you use this gem (5.x) with Sidekiq >= 6. It may work with sidekiq 4/5, but if something needs to be fixed to work with those older versions, we won't fix it since we dropped support for those versions of sidekiq.

btw, I just released v5.0.2 fixing the dependency requirement. Thanks for reporting!
